server:
  port: 8080
  address: 0.0.0.0
spring:
  data:
    redis:
      host: 3.35.97.18
      port: 6379
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        #        dialect: org.hibernate.dialect.MySQLDialect
        transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
    open-in-view: false

cloud:
  aws:
    s3:
      bucket: went-back
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secretKey: ${JWT_SECRET_KEY}
  playerTokenExpiration: 60000 # 60 * 1000  #
  accessExpiration: 3600000 # 30000  #
  refreshExpiration: 604800000 # 60000 #
  aesKey: ${JWT_AES_KEY}



oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}

  kakao:
    app-id: ${KAKAO_APP_ID}
    client-id: ${KAKAO_CLIENT_ID}
    redirect-url: ${KAKAO_REDIRECT_URL}
    client-secret: ${KAKAO_CLIENT_SECRET}
    base-url: ${KAKAO_BASE_URL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring.output.ansi.enabled: always